//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace AzulBodas.Data.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class AzulBodasEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new AzulBodasEntities object using the connection string found in the 'AzulBodasEntities' section of the application configuration file.
        /// </summary>
        public AzulBodasEntities() : base("name=AzulBodasEntities", "AzulBodasEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AzulBodasEntities object.
        /// </summary>
        public AzulBodasEntities(string connectionString) : base(connectionString, "AzulBodasEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AzulBodasEntities object.
        /// </summary>
        public AzulBodasEntities(EntityConnection connection) : base(connection, "AzulBodasEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Text> Texts
        {
            get
            {
                if ((_Texts == null))
                {
                    _Texts = base.CreateObjectSet<Text>("Texts");
                }
                return _Texts;
            }
        }
        private ObjectSet<Text> _Texts;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Texts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTexts(Text text)
        {
            base.AddObject("Texts", text);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AzulBodasModel", Name="Text")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Text : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Text object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Text CreateText(global::System.Int32 id)
        {
            Text text = new Text();
            text.Id = id;
            return text;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DescriptionSpanish
        {
            get
            {
                return _DescriptionSpanish;
            }
            set
            {
                OnDescriptionSpanishChanging(value);
                ReportPropertyChanging("DescriptionSpanish");
                _DescriptionSpanish = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DescriptionSpanish");
                OnDescriptionSpanishChanged();
            }
        }
        private global::System.String _DescriptionSpanish;
        partial void OnDescriptionSpanishChanging(global::System.String value);
        partial void OnDescriptionSpanishChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DescriptionEnglish
        {
            get
            {
                return _DescriptionEnglish;
            }
            set
            {
                OnDescriptionEnglishChanging(value);
                ReportPropertyChanging("DescriptionEnglish");
                _DescriptionEnglish = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DescriptionEnglish");
                OnDescriptionEnglishChanged();
            }
        }
        private global::System.String _DescriptionEnglish;
        partial void OnDescriptionEnglishChanging(global::System.String value);
        partial void OnDescriptionEnglishChanged();

        #endregion
    
    }

    #endregion
    
}
